velib_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ZZHNGGJ-MPB61332
      user: DBT_USER
      password: "Velib2026!"
      role: DATA_ENGINEER
      warehouse: VELIB_WH
      database: VELIB_STAGING
      schema: STAGING
      threads: 1
      client_session_keep_alive: false
