global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  # Métriques Airflow via StatsD exporter
  - job_name: airflow
    static_configs:
      - targets: ["statsd-exporter:9102"]
        labels:
          env: local

  # Métriques système des containers Docker
  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          env: local

  # Métriques containers VM Airflow
  - job_name: cadvisor_airflow
    static_configs:
      - targets: ["34.22.120.14:8081"]
        labels:
          env: local
          vm: airflow

  # Prometheus lui-même
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
